language: cpp

compiler:
  - gcc

sudo: false

addons:
  apt:
    packages:
    - cmake

install:
  - mkdir cmake
  - cd cmake
  - wget -qO- http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz | tar xvz
  - cd ..

script:
  - mkdir build
  - cd build
  - ../cmake/cmake-3.1.0-Linux-x86_64/bin/cmake ../
  - make -j4
  - ./HPCsim/HPCsim -e 100 -s examples/Pi/libPi.so
  - cd ../
  - mkdir build_pilot
  - cd build_pilot
  - ../cmake/cmake-3.1.0-Linux-x86_64/bin/cmake -DUSE_PILOT_THREAD=1 ../
  - make -j4
  - ./HPCsim/HPCsim -e 100 -s examples/Pi/libPi.so
  - ./examples/Pi/ComparePi ../build/HPCsim.out ./HPCsim.out
  - cd ../
  - cd build
  - rm -f ./HPCsim.out
  - ./HPCsim/HPCsim -e 50 -s examples/Pi/libPi.so
  - ./HPCsim/HPCsim -c -e 100 -s examples/Pi/libPi.so
  - ./examples/Pi/ComparePi ./HPCsim.out ../build_pilot/HPCsim.out
